[data]
data_dir = "./data/cifar10"
batch_size = 64
val_split = 0.2
test_split = 1
img_size = 32
num_workers = 0

[model]
filters = 64
num_layers = 3
kernel_size = 3
maxpool = 2
units1 = 128
units2 = 64
dropout = 0.2
num_classes = 10

[train]
learning_rate = 0.01
epochs = 3
optimizer = "adam"
train_steps = 100
valid_steps = 40
logdir = "logs"

[logging]
logdir = "logs"
checkpoint_dir = "models"
save_interval = 1
report_types = ["TOML", "MLFLOW"]
experiment_name = "testing"
model = "original_model"
developer = "Marcello"